# Generated by Django 6.0.1 on 2026-01-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_hash', models.CharField(max_length=66, unique=True)),
                ('sender', models.CharField(max_length=42)),
                ('receiver', models.CharField(max_length=42)),
                ('amount', models.CharField(max_length=50)),
                ('message', models.TextField(blank=True)),
                ('network', models.CharField(default='sepolia', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
